### ISSUE TITLE
impatest on 32-bit architecture gives: client.c:153:7: error: too many arguments to function ‘io_stream_create_ssl_client’

### ISSUE THREAD

**Issue by spijoing** [dovecot/imaptest#32]
I work with i686 32-bit architecture, ubuntu 16.04.7, dovecot 2.3.21 (47349e2482) and the latest imaptest server. Having tried "static binary of imaptest (built on Ubuntu 22.04). " That "should work on any modern Linux machine using libc." I get my machine is not modern because after failing to run with docker I try 'make' and get

 make
make  all-recursive
make[1]: Entering directory '/usr/local/src/imaptest-latest'
Making all in src
make[2]: Entering directory '/usr/local/src/imaptest-latest/src'
  CC       imaptest-checkpoint.o
  CC       imaptest-client.o
client.c: In function ‘client_wait_connect’:
client.c:155:7: warning: passing argument 5 of ‘io_stream_create_ssl_client’ from incompatible pointer type [-Wincompatible-pointer-types]
       &client->input, &client->output,
       ^
In file included from client.c:9:0:
/usr/local/include/dovecot/iostream-ssl.h:58:5: note: expected ‘struct ostream **’ but argument is of type ‘struct istream **’
 int io_stream_create_ssl_client(struct ssl_iostream_context *ctx, const char *host,
     ^
client.c:155:23: warning: passing argument 6 of ‘io_stream_create_ssl_client’ from incompatible pointer type [-Wincompatible-pointer-types]
       &client->input, &client->output,
                       ^
In file included from client.c:9:0:
/usr/local/include/dovecot/iostream-ssl.h:58:5: note: expected ‘struct ssl_iostream **’ but argument is of type ‘struct ostream **’
 int io_stream_create_ssl_client(struct ssl_iostream_context *ctx, const char *host,
     ^
client.c:156:7: warning: passing argument 7 of ‘io_stream_create_ssl_client’ from incompatible pointer type [-Wincompatible-pointer-types]
       &client->ssl_iostream, &error) < 0)
       ^
In file included from client.c:9:0:
/usr/local/include/dovecot/iostream-ssl.h:58:5: note: expected ‘const char **’ but argument is of type ‘struct ssl_iostream **’
 int io_stream_create_ssl_client(struct ssl_iostream_context *ctx, const char *host,
     ^
client.c:153:7: error: too many arguments to function ‘io_stream_create_ssl_client’
   if (io_stream_create_ssl_client(ssl_ctx, conf.host, &conf.ssl_set,
       ^
In file included from client.c:9:0:
/usr/local/include/dovecot/iostream-ssl.h:58:5: note: declared here
 int io_stream_create_ssl_client(struct ssl_iostream_context *ctx, const char *host,
     ^
Makefile:634: recipe for target 'imaptest-client.o' failed
make[2]: *** [imaptest-client.o] Error 1
make[2]: Leaving directory '/usr/local/src/imaptest-latest/src'
Makefile:485: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/imaptest-latest'
Makefile:413: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by spijoing** [comment]
I did not, and was able to compile with release-2.3. Thank you for your quick reply and for your patience.
